[package]
name = "dusk-merlin"
# Before incrementing:
# - update CHANGELOG
# - update html_root_url
# - update README if required by semver
version = "3.0.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2024"
rust-version = "1.96.1"
readme = "README.md"
license = "MIT"
repository = "https://github.com/dusk-network/merlin"
homepage = "https://github.com/dusk-network/merlin"
documentation = "https://docs.rs/dusk-merlin"
categories = ["cryptography"]
keywords = ["cryptography", "zero-knowledge", "fiat-shamir", "transcript"]
description = "Composable proof transcripts for public-coin arguments of knowledge"
exclude = [".gitignore"]

[lib]
name = "merlin"

[dependencies]
keccak = { version = "0.1.0", default-features = false }
zeroize = { version = "1.8", default-features = false, features = ["zeroize_derive"] }
rand_core = { version = "0.6.4", default-features = false }
hex = { version = "0.4.3", default-features = false, features = ["alloc"], optional = true }

[dev-dependencies]
strobe-rs = "0.13"
rand_chacha = "0.3"

[features]
default = ["std"]
debug-transcript = ["dep:hex", "std"]
std = ["rand_core/std"]
